// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/bookings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/bookings/index.get').default>>>>
    }
    '/api/admin/bookings/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/bookings/stats.get').default>>>>
    }
    '/api/admin/properties/:id/approve': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/properties/[id]/approve.patch').default>>>>
    }
    '/api/admin/properties/:id/reject': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/properties/[id]/reject.patch').default>>>>
    }
    '/api/admin/properties': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/properties/index.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.get').default>>>>
    }
    '/api/auth/refresh': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/refresh.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/bookings/:id/activate': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/activate.patch').default>>>>
    }
    '/api/bookings/:id/complete': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/complete.patch').default>>>>
    }
    '/api/bookings/:id/confirm': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/confirm.patch').default>>>>
    }
    '/api/bookings/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/index.put').default>>>>
    }
    '/api/bookings/:id/logs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/logs/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/logs/index.post').default>>>>
    }
    '/api/bookings/:id/reject': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]/reject.patch').default>>>>
    }
    '/api/bookings': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/index.post').default>>>>
    }
    '/api/bookings/my-bookings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/my-bookings.get').default>>>>
    }
    '/api/profile': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.put').default>>>>
    }
    '/api/properties/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/[id]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/[id]/index.put').default>>>>
    }
    '/api/properties/:id/status': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/[id]/status.patch').default>>>>
    }
    '/api/properties/cities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/cities.get').default>>>>
    }
    '/api/properties': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/index.post').default>>>>
    }
    '/api/properties/my-properties': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/my-properties.get').default>>>>
    }
    '/api/properties/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/search.get').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/index.put').default>>>>
    }
    '/api/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index').default>>>>
    }
    '/api/users/me': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/me/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/me/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/me/index.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}